/* groovylint-disable GStringExpressionWithinString, LineLength */
pipeline {
   agent {
      kubernetes {
        yaml """
        apiVersion: v1
        kind: Pod
        metadata:
          name: QA-cloudbees-saas-smoketest
        spec:
          containers:
          - name: devops-cli
            image: us-east1-docker.pkg.dev/cloudbees-artifact-registry/common/devops-cli:latest
            alwaysPullImage: true
            command:
            - cat
            tty: true
            resources:
              requests:
                memory: "200Mi"
                cpu: "200m"
              limits:
                memory: "300Mi"
                cpu: "300m"
        """
      }
    }

    triggers {
        cron('*/5 * * * *')
    }

    options {
        buildDiscarder(logRotator(numToKeepStr:'50'))
        timeout(time: 1, unit: 'MINUTES')
        disableConcurrentBuilds()
    }

    stages {
        stage('Heartbeat') {
          steps {
            container('devops-cli') {
              withCredentials([usernamePassword(credentialsId: 'gauntlet3-ops-github-app',
                               usernameVariable: 'GITHUB_APP',
                               passwordVariable: 'GITHUB_ACCESS_TOKEN')]) {
                sh '''
                  BOT=cloudbees-operations-rw-g3
                  env | grep GIT
                  git remote remove origin || true
                  git remote add origin https://x-access-token:${GITHUB_ACCESS_TOKEN}@github.com/apandharkar/demo-app
                  # Get ID with: curl --silent 'https://api.github.com/users/cloudbees-operations-rw-g3[bot]' | jq -r '.id'
                  git config --global user.name 'cloudbees-operations-rw-g3[bot]'
                  git config --global user.email '80285927+cloudbees-operations-rw-g3[bot]@users.noreply.github.com'

                  make heartbeat
                '''
              }
            }
          }
        }
    }
}