apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - '**'

jobs:
  ci-job:
    outputs:
      preprod-changes: ${{ steps.changes.outputs.preprod-changes }}
      prod-changes: ${{ steps.changes.outputs.prod-changes }}
    steps:
      - uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace
      - name: checkout
        uses: cloudbees-io/checkout@v1
      - name: Run tests
        id: changes
        uses: docker://alpine/git:latest
        run: |
          echo "false" > $CLOUDBEES_OUTPUTS/preprod-changes
          echo "true" > $CLOUDBEES_OUTPUTS/prod-changes
  preprod-deploy:
    needs: [ci-job]
    steps:
      - uses: docker://alpine/git:latest
        run: |
           if ["${{ needs.ci-job.outputs.preprod-changes }}" == "true"]; then
              echo "Deploying preprod"
           fi
  prod-deploy:
    needs: [ci-job]
    steps:
      - uses: docker://alpine/git:latest
        run: |
           if ["${{ needs.ci-job.outputs.prod-changes }}" == "true"]; then
            echo "Deploying prod"
           fi