apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - '**'

jobs:
  ci-job:
    permissions:
      scm-token-own: read
    outputs:
      preprod-changed: ${{ steps.changes.outputs.preprod-changed }}
    steps:
      - uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace
      - name: checkout
        uses: cloudbees-io/checkout@v1
      - name: Run tests
        uses: docker://alpine/git:latest
        run: |
          set +x
          git log -1 --stat | grep -c "cloudbees/workflows/my-workflow.yaml"
          if  [ $(git log -1 --stat | grep -c "cloudbees/workflows/my-workflow.yaml") == "1" ]; then
            echo "Preprod Changes"
            echo "true" > $CLOUDBEES_OUTPUTS/preprod-changed 
          else
            echo "no preprod changes"
            preprod_changes=False
          fi
  preprod-deploy:
    needs:
      - ci-job
    if: ${{ !!jobs.ci-job.outputs.preprod-changed }}
    permissions:
      scm-token-own: read
      scm-token-org: read
      id-token: write
    steps:
      - uses: cloudbees-io/checkout@v1
        run:
           echo "hello"