apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - '**'

jobs:
  ci-job:
    outputs:
      preprod-changes: ${{ steps.changes.outputs.preprod-changes }}
      prod-changes: ${{ steps.changes.outputs.prod-changes }}
    steps:
      - name: Run tests
        id: changes
        uses: docker://alpine/git:latest
        env:
          iam_role: "${{ cloudbees.version }}{{ cloudbees.scm.branch == main && '' || -cloubees.scm.branch }}"
        run: |
          echo $iam_role
