apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow 2
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
env:
  is_main_branch: ${{ vars.foo }}

jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          env
