apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - '**'

jobs:
  ci-job:
    outputs:
      preprod-changes: ${{ steps.changes.outputs.preprod-changes }}
      prod-changes: ${{ steps.changes.outputs.prod-changes }}
    steps:
      - uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace
      - name: checkout
        uses: cloudbees-io/checkout@v1
      - name: Run tests
        id: changes
        uses: docker://alpine/git:latest
        env:
          iam_role: ${{ vars.oidc_staging_iam_role }}
        run: |
          ls -ltr
          git branch
          git diff --name-only HEAD^ HEAD
