apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://020229604682-golang:1.20.3-alpine3.17-test
        shell: sh
        run: |
          echo "hello world"
