apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - '**'

jobs:
  ci-job:
    outputs:
      preprod-changed: ${{ steps.changes.outputs.preprod-changed }}
    steps:
      - uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace
      - name: checkout
        uses: cloudbees-io/checkout@v1
      - name: Run tests
        id: changes
        uses: docker://alpine/git:latest
        run: |
          echo "true" > $CLOUDBEES_OUTPUTS/preprod-changed
  preprod-deploy:
    needs: [ci-job]
    if: ${{ needs.ci-job.outputs.preprod-changed }}
    steps:
      - uses: docker://alpine/git:latest
        run:
           echo "$CLOUDBEES_OUTPUTS"